services:

  adminer:
    image: adminer
    container_name: hypertube_adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - hypertube
    depends_on:
      - database

  front:
    build: setup/frontend
    image: hypertube_front
    container_name: hypertube_front
    restart: on-failure
    volumes:
      - ${PWD}/srcs/frontend:/var/www/html
    expose:
      - 3000
    networks:
      - hypertube
    depends_on:
      - back
    env_file:
      - .env.dev

  back:
    build: setup/backend
    image: hypertube_back
    container_name: hypertube_back
    restart: on-failure
    volumes:
      - ${PWD}/srcs/backend:/var/www/html
    expose:
      - 8080
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "20000:20000/udp"
    networks:
      - hypertube
    depends_on:
      - database
    env_file:
      - .env.dev

  database:
    image: postgres
    container_name: hypertube_database
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
    # volumes:
    #   - vol_database:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - hypertube
    env_file:
      - .env.dev

  web:
    image: nginx:alpine
    container_name: hypertube_web
    restart: always
    volumes:
      - ./setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8081:80
    networks:
      - hypertube
    depends_on:
      - back
      - front

  redis:
    image: redis:latest
    container_name: matcha_redis
    command: redis-server --appendonly yes
    restart: on-failure
    # volumes:
    #   - redis_data:/data 
    # ports:
    #   - 6379:6379
    networks:
      - hypertube

networks:
  hypertube:
    driver: bridge

